repository_type: pipeline

nf_core_version: 3.3.2

lint: {}

template:
  org: nf-core
  name: fastqfetcher
  description: A simple, yet efficient workflow to download SRA data using sratools
  author: Haibo Liu
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
